name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for opening an issue!"
        pr-message: "Thanks for raising a PR! Please make sure you've read CONTRIBUTING.md to ensure your PR meets the community guidelines."
